### ISSUE TITLE
Not working with HTTPS load balancers

### ISSUE THREAD

**Issue by kpkristjansson** [cboscolo/elb2loggly#7]
Hey,
There are some additional columns needed to make this work with HTTPS load balancers
Here is an example log line from AWS ELB using HTTPS:
<code>2015-07-23T10:45:34.971531Z LoadBalancerName xxx.xxx.xxx.xxx:12345 xx.xxx.xxx.xxx:80 0.000039 0.004119 0.000024 200 200 0 2316 "GET https://www.example.com:443/ HTTP/1.1" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2</code>
user_agent, ssl_cipher and ssl_protocol are missing

**Comment by mostlyjason** [comment]
I think this comment might address it https://github.com/ssayala/elb2loggly/commit/67ab09a170c6bc5e351d0241f09b54b45966b04f. Would need to do a PR though.

**Comment by kpkristjansson** [comment]
I've tested it and it works perfectly :)

**Comment by cboscolo** [comment]
Have you tested that the code continues to work with HTTP-based requests?  

I'm a little confused by the AWS log format documentation.  Our logs don't match the examples in their doc.

Here is a description of of the ELB log format:
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html#log-processing

Here is the example of HTTP:

```
2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.000073 0.001048 0.000057 200 200 0 29 "GET http://www.example.com:80/ HTTP/1.1" "curl/7.38.0" - -
```

Notice the: `"curl/7.38.0" - -`

But, the HTTP logs from our ELB does not have those last three fields:

```
2015-07-29T23:59:00.359044Z prod-mobile-elb 67.228.213.178:54030 10.1.90.66:80 0.000044 0.002069 0.000023 200 200 0 40 "GET https://api.xxx.com:443/api/health HTTP/1.1"
```

I will do some investigation to see this is somehow controlled with an AWS setting, otherwise the logic will need to handle parsing both HTTP format with 12 columns and HTTPS logs format with 15 columns.

**Comment by kpkristjansson** [comment]
Hey,
Yeah, I tested both HTTP and HTTPS.
Here is the raw out from Loggly.
<b>HTTP:</b>
{
  "timestamp": "2015-07-30T10:30:16.192518Z",
  "elb": "test-elb-http",
  "client_ip": "xxx.xxx.xxx.xxx",
  "client_port": "54150",
  "backend": "xxx.xxx.xxx.xxx",
  "backend_port": "80",
  "request_processing_time": "0.000034",
  "backend_processing_time": "0.001293",
  "response_processing_time": "0.000015",
  "elb_status_code": "304",
  "backend_status_code": "304",
  "received_bytes": "0",
  "sent_bytes": "0",
  "request_method": "GET",
  "request_url": "http://www.example.com:80/images/image.gif",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0",
  "ssl_cipher": "-",
  "ssl_protocol": "-"
}

<b>HTTPS:</b>
{
  "timestamp": "2015-07-30T19:39:22.079362Z",
  "elb": "test-elb-https",
  "client_ip": "xxx.xxx.xxx.xxx",
  "client_port": "4139",
  "backend": "xxx.xxx.xxx.xxx",
  "backend_port": "80",
  "request_processing_time": "0.000055",
  "backend_processing_time": "0.035728",
  "response_processing_time": "0.000038",
  "elb_status_code": "200",
  "backend_status_code": "200",
  "received_bytes": "0",
  "sent_bytes": "3964",
  "request_method": "GET",
  "request_url": "https://www.example.com:80/images/image.gif",
  "user_agent": "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)",
  "ssl_cipher": "ECDHE-RSA-AES128-SHA",
  "ssl_protocol": "TLSv1"
}

**Comment by cboscolo** [comment]
@kpkristjansson, out of curiosity, did you use the AWS console or the command-line tools to config your ELB to do logging?  I am stumped trying to figure out why our ELBs are not logging the user_agent, ssl_cipher nor ssl_protocol.

Looks like others may have run into this as well:
http://stackoverflow.com/questions/31709876/aws-elb-logs-missing-user-agent-and-tls-cipher-fields

**Comment by kpkristjansson** [comment]
@cboscolo - I'm using a CloudFormation template that activates ELB logging.  I haven't tested it using the AWS Console.

**Comment by ctrlrsf** [comment]
@cboscolo Our ELBs were created from the console and I'm seeing similar issue. One ELB is sending both types of logs (with and without the user agent and SSL fields). This ELB was created in Nov 2014, so perhaps some of the actual ELB instances are logging with the old format still. I believe the script should be able to handle both log formats.

I tested https://github.com/cboscolo/elb2loggly/pull/8 and it works fine when the user agent and SSL fields are present, but it logs an uncaught exception when it sees a line with 12 fields instead of 15.

Reason it throws that exception is due to the line below. The string passed to done() is the actual error string.
https://github.com/ssayala/elb2loggly/blob/master/elb2loggly.js#L86

I changed it to call done() and use console.error() instead to see that it was trying to process a line with 12 fields instead of 15.

**Comment by cboscolo** [comment]
Doesn't look like there is anything you can do on your own.

According to AWS support: "We are in the process of rolling out these new access log fields to existing Elastic Load Balancers. Any newly created Elastic Load Balancers will have these fields present."

https://forums.aws.amazon.com/thread.jspa?messageID=659342
